title: BRAHIM ALAMI # your name (or website title) here
logo: "/images/profil pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  -Business Analyst and machine learning enthousiast, I enjoy leveraging growth through data, as well as being part of R&D projects. Business and finance background, with mathematical and computer sciences fundations.
  <br><br>
  - bachelor of Mathemtics : La sorbonne université
  <br><br>
  - Business School: SKEMA
  <br><br>
  - Data Science certification : MIT
  <br><br>
  currently teaching Data Science at LeWagon 
  <br><br>
  
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
 
 [![](https://img.shields.io/badge/Github-code-color?logo=linkedin)](https://www.linkedin.com/in/brahim-alami-hassani/)
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
