title: BRAHIM ALAMI # your name (or website title) here
logo: "/images/profil pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Business Analyst and machine learning enthousiast, I enjoy leveraging growth through data, as well as being part of R&D projects.
  <br><br>
  currently teaching Data Science @ LeWagon
  <ul>
  <li> Bachelor of Mathemtics : La Sorbonne Université</li>
  <li> Business School: SKEMA</li>
  <li> Data Science certification : MIT</li>
  </ul>
  <a href="https://www.linkedin.com/in/brahim-alami-hassani/">View My LinkedIn Profile</a> 
  

theme: jekyll-theme-minimal
google_analytics: G-08V6E4Q5K6 # your Google Analytics tracking ID here
